### ISSUE TITLE
0.4.0 thoughts

### ISSUE THREAD

**Issue by adamkittelson** [oestrich/gossip-elixir#6]
Couple thoughts while getting the new 0.4.0 features working on Apotheosis (tells and request players online).

Doing a call for sending a tell is super rad, would be good to document that Gossip.send_tell/4 has an actionable return value (`:ok` if it worked, `{:error, some_error}` otherwise I believe)

Second thing is since you've now got the call-over-websockets technology working it might be cool to have Gossip.request_players_online/0 act as a call and return a response instead of sending a series of discrete messages for the Client.players_status/2 callback. Failing that it would be good to specify in the documentation for Gossip.request_players_online/0 that Client.players_status/2 is the callback that will be hit (it currently just says "You will get a callback per game that is online.")

**Comment by oestrich** [comment]
Updated the docs to reflect these, it was me being lazy. I can push a 0.4.1 so hexdocs is up to date.

I'm not sure we can get away with `request_players_online` doing a call, since we don't know how many games will be returned as separate messages.

**Comment by oestrich** [comment]
I think this is fixed now? Closing due to age.
